import { dmSans } from "@/lib/fonts";
import type { Metadata } from "next";
import ScrollHeader from "./components/scroll-header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>
        <ScrollHeader />
        {children}
      </body>
    </html>
  );
}
